### ISSUE TITLE
Quarryshop

### ISSUE THREAD

**Issue by AthulaDissanayaka** [ranilplus/Serenity-Trust#3]
Can you check about the quaryshop web backup. We need to activate it in a different provider. Can you let me know asap. Thanks

**Comment by ranilplus** [comment]
http://arclanka.com/quarryshop/

getting thequarryshop.biz adress back , webspace and configuration
close to Rs 5000/= 
after deposit money i'll get back the domain name and put site online and create email accounts.

**Comment by AthulaDissanayaka** [comment]
Do not spend any time on quarryshop request as there is a time strain on this issue. I have spoken to Ravi. So for the time been this issue is closed. No action required until further notice.
